sonar.projectKey=john19968010_Kevin_112504009
sonar.organization=john19968010
sonar.projectName=Kevin_112504009
sonar.sources=asgards
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.python.xunit.reportPath=junit/test-results.xml
sonar.python.coverage.reportPaths=coverage.xml
