trigger:
  batch: true
  branches:
    include:
      - main
      - '*'

pr:
  branches:
    include:
      - main
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  sonarConnectionName: 'SonarCloudTest'
  sonarProjectKey: 'john19968010_Kevin_112504009'
  sonarProjectName: 'Kevin_112504009'
  sonarOrganization: 'john19968010'

stages:
- stage: Build
  displayName: 'Build and Validation'
  jobs:
  - job: Validate
    displayName: 'Lint and Test'
    steps:
    - checkout: self
      fetchDepth: 0

    - template: templates/install-deps.yml
    - template: templates/run-tests.yml

- stage: Analyze
  displayName: 'Quality Analysis'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: SonarCloud
    displayName: 'SonarCloud Scan'
    steps:
    - checkout: self
      fetchDepth: 0

    - template: templates/install-deps.yml
    - template: templates/sonarqube-analysis.yml